/**
 * Development and test fixture.
 *
 * Generated from the design handoff's own catalogue (`design-handoff/data/`)
 * so the fixture mirrors the designed shop exactly: 27 products across five
 * collections, each product's sizes expressed as Shopify-shaped variants.
 *
 * This is NOT a production fallback. It is served only when
 * OPHELIA_FORCE_LOCAL_CATALOGUE=true, it refuses to run on a production
 * deployment, and checkout is disabled on it — see lib/commerce/config.ts.
 */

import type { Collection, Product } from '@/lib/commerce/types';

const EUR = 'EUR';

function money(amount: number) {
  return { amount: amount.toFixed(2), currencyCode: EUR };
}

function image(url: string, altText: string) {
  return { url, altText, width: 1067, height: 1600 };
}

export const FIXTURE_COLLECTIONS: Collection[] = [
  {
    id: 'gid://fixture/Collection/cookies',
    handle: "cookies",
    title: "cookies",
    description: '',
    descriptionHtml: '',
    image: null,
    seo: { title: null, description: null },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Collection/mercearia',
    handle: "mercearia",
    title: "mercearia",
    description: '',
    descriptionHtml: '',
    image: null,
    seo: { title: null, description: null },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Collection/cafe',
    handle: "cafe",
    title: "caf\u00e9, chai & matcha",
    description: '',
    descriptionHtml: '',
    image: null,
    seo: { title: null, description: null },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Collection/bolos',
    handle: "bolos",
    title: "bolos",
    description: '',
    descriptionHtml: '',
    image: null,
    seo: { title: null, description: null },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Collection/casa',
    handle: "casa",
    title: "casa & presentes",
    description: '',
    descriptionHtml: '',
    image: null,
    seo: { title: null, description: null },
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

/** Collection handle → product handles, in display order. */
export const FIXTURE_COLLECTION_PRODUCTS: Record<string, string[]> = {
  "cookies": ["ophelia-cookies-ny", "ophelia-cookies", "ophelia-cookiebrownie", "ophelia-cookie-banoffee", "pack-especial-de-cookies", "cookies-personalizadas"],
  "mercearia": ["o-azeite-da-ophelia", "mel-de-rosmaninho", "mel-de-carvalho", "doce-de-alperce-e-amendoa", "doce-de-maca-e-vinho-do-porto", "doce-de-pera-e-gengibre", "doce-de-morango-com-baunilha", "a-granola-da-ophelia"],
  "cafe": ["cafe-da-ophelia-em-grao", "cafe-da-ophelia-em-po", "chai-da-ophelia", "matcha-da-ophelia"],
  "bolos": ["bolo-de-chocolate-e-framboesa", "pavlova-de-frutos-vermelhos", "bolo-red-velvet", "bolo-merengue-de-caramelo", "cheesecake-de-frutos-silvestres", "panetone-de-chocolate"],
  "casa": ["vela-aromatica-croissant", "avental-da-ophelia", "cartao-personalizado"],
};

export const FIXTURE_PRODUCTS: Product[] = [
  {
    id: 'gid://fixture/Product/ny',
    handle: "ophelia-cookies-ny",
    title: "Ophelia Cookies NY",
    description: "As famosas cookies da Ophelia \u2014 direto da nossa cozinha para a tua casa. Cada caixa de presente \u00e9 preparada sob encomenda. V\u00eam embaladas individualmente em saquinhos de celofane com o nosso adesivo e colocadas nas nossas caixas azuis ou brancas. \u00c9 o presente perfeito!",
    descriptionHtml: "<p>As famosas cookies da Ophelia \u2014 direto da nossa cozinha para a tua casa. Cada caixa de presente \u00e9 preparada sob encomenda. V\u00eam embaladas individualmente em saquinhos de celofane com o nosso adesivo e colocadas nas nossas caixas azuis ou brancas. \u00c9 o presente perfeito!</p>",
    productType: "cookies",
    vendor: 'Ophelia',
    tags: ["a mais pedida"],
    availableForSale: true,
    featuredImage: image('/photos/g1.jpeg', "Ophelia Cookies NY"),
    images: [
      image('/photos/g1.jpeg', "Ophelia Cookies NY"),
      image('/photos/c01.jpg', "Ophelia Cookies NY"),
      image('/photos/g2.jpeg', "Ophelia Cookies NY"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/ophelia-cookies-ny',
        name: "escolhe as cookies",
        values: ["6 unidades", "8 unidades", "12 unidades"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookies-ny-0',
        title: "6 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(30),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "6 unidades" }],
        sku: "ny-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookies-ny-1',
        title: "8 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(40),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "8 unidades" }],
        sku: "ny-2",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookies-ny-2',
        title: "12 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(60),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "12 unidades" }],
        sku: "ny-3",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(30),
      maxVariantPrice: money(60),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "cookies",
      badge: "a mais pedida",
      shortDescription: null,
      ingredients: "Farinha, chocolate 70%, chocolate 36,5%, manteiga, a\u00e7\u00facar amarelo, a\u00e7\u00facar branco, ovos, gemas, baunilha, bicarbonato, fermento, sal. Cada cookie cont\u00e9m 150 gramas.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/classicas',
    handle: "ophelia-cookies",
    title: "Ophelia Cookies",
    description: "Sabores dispon\u00edveis: tradicional, red velvet, cacau e lim\u00e3o. Preparadas sob encomenda, embaladas uma a uma com o nosso adesivo exclusivo e colocadas nas nossas caixas azuis ou brancas.",
    descriptionHtml: "<p>Sabores dispon\u00edveis: tradicional, red velvet, cacau e lim\u00e3o. Preparadas sob encomenda, embaladas uma a uma com o nosso adesivo exclusivo e colocadas nas nossas caixas azuis ou brancas.</p>",
    productType: "cookies",
    vendor: 'Ophelia',
    tags: ["4 sabores"],
    availableForSale: true,
    featuredImage: image('/photos/g2.jpeg', "Ophelia Cookies"),
    images: [
      image('/photos/g2.jpeg', "Ophelia Cookies"),
      image('/photos/g1.jpeg', "Ophelia Cookies"),
      image('/photos/c06.jpg', "Ophelia Cookies"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/ophelia-cookies',
        name: "escolhe as cookies",
        values: ["4 unidades", "8 unidades", "12 unidades"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookies-0',
        title: "4 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(17),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "4 unidades" }],
        sku: "classicas-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookies-1',
        title: "8 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(32),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "8 unidades" }],
        sku: "classicas-2",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookies-2',
        title: "12 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(48),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "12 unidades" }],
        sku: "classicas-3",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(17),
      maxVariantPrice: money(48),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "cookies",
      badge: "4 sabores",
      shortDescription: null,
      ingredients: "Farinha, chocolate 70%, chocolate 36,5%, chocolate branco, manteiga, a\u00e7\u00facar amarelo, a\u00e7\u00facar branco, ovos, gemas, baunilha, bicarbonato, fermento, sal, cacau, corante vermelho, leite em p\u00f3, amido de milho, lim\u00e3o. Cada cookie cont\u00e9m 100 gramas.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/cookiebrownie',
    handle: "ophelia-cookiebrownie",
    title: "Ophelia CookieBrownie",
    description: "Crocante por fora e muito cremosa por dentro. N\u00e3o cont\u00e9m farinha. Preparada sob encomenda e embalada individualmente nas nossas caixas azuis ou brancas.",
    descriptionHtml: "<p>Crocante por fora e muito cremosa por dentro. N\u00e3o cont\u00e9m farinha. Preparada sob encomenda e embalada individualmente nas nossas caixas azuis ou brancas.</p>",
    productType: "cookies",
    vendor: 'Ophelia',
    tags: ["sem farinha"],
    availableForSale: true,
    featuredImage: image('/photos/g2.jpeg', "Ophelia CookieBrownie"),
    images: [
      image('/photos/g2.jpeg', "Ophelia CookieBrownie"),
      image('/photos/c01.jpg', "Ophelia CookieBrownie"),
      image('/photos/g1.jpeg', "Ophelia CookieBrownie"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/ophelia-cookiebrownie',
        name: "escolhe as cookies",
        values: ["4 unidades", "8 unidades", "12 unidades"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookiebrownie-0',
        title: "4 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(20),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "4 unidades" }],
        sku: "cookiebrownie-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookiebrownie-1',
        title: "8 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(40),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "8 unidades" }],
        sku: "cookiebrownie-2",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookiebrownie-2',
        title: "12 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(57),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "12 unidades" }],
        sku: "cookiebrownie-3",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(20),
      maxVariantPrice: money(57),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "cookies",
      badge: "sem farinha",
      shortDescription: null,
      ingredients: "Chocolate 70%, manteiga, a\u00e7\u00facar, ovos, cacau. Cada cookie cont\u00e9m 100 gramas.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/banoffee',
    handle: "ophelia-cookie-banoffee",
    title: "Ophelia Cookie Banoffee",
    description: "A grande novidade deste m\u00eas: banana e doce de leite dentro da nossa massa de cookie. Preparada sob encomenda e embalada uma a uma.",
    descriptionHtml: "<p>A grande novidade deste m\u00eas: banana e doce de leite dentro da nossa massa de cookie. Preparada sob encomenda e embalada uma a uma.</p>",
    productType: "cookies",
    vendor: 'Ophelia',
    tags: ["novidade"],
    availableForSale: true,
    featuredImage: image('/photos/g1.jpeg', "Ophelia Cookie Banoffee"),
    images: [
      image('/photos/g1.jpeg', "Ophelia Cookie Banoffee"),
      image('/photos/g2.jpeg', "Ophelia Cookie Banoffee"),
      image('/photos/c11.jpg', "Ophelia Cookie Banoffee"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/ophelia-cookie-banoffee',
        name: "escolhe as cookies",
        values: ["4 unidades", "8 unidades", "12 unidades"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookie-banoffee-0',
        title: "4 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(20),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "4 unidades" }],
        sku: "banoffee-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookie-banoffee-1',
        title: "8 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(40),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "8 unidades" }],
        sku: "banoffee-2",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/ophelia-cookie-banoffee-2',
        title: "12 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(57),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "12 unidades" }],
        sku: "banoffee-3",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(20),
      maxVariantPrice: money(57),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "cookies",
      badge: "novidade",
      shortDescription: null,
      ingredients: "Chocolate ao leite, a\u00e7\u00facar mascavo, a\u00e7\u00facar branco, manteiga, farinha, ovos, sal, bicarbonato, amido de milho, leite em p\u00f3, banana, doce de leite. Cada cookie cont\u00e9m 100 gramas.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/pack',
    handle: "pack-especial-de-cookies",
    title: "Pack Especial de Cookies",
    description: "Um mix das nossas favoritas: cookie banoffee, cookiebrownie e cookie cheesecake. Para quem n\u00e3o consegue escolher \u2014 e faz muito bem.",
    descriptionHtml: "<p>Um mix das nossas favoritas: cookie banoffee, cookiebrownie e cookie cheesecake. Para quem n\u00e3o consegue escolher \u2014 e faz muito bem.</p>",
    productType: "cookies",
    vendor: 'Ophelia',
    tags: ["mix de sabores"],
    availableForSale: true,
    featuredImage: image('/photos/g1.jpeg', "Pack Especial de Cookies"),
    images: [
      image('/photos/g1.jpeg', "Pack Especial de Cookies"),
      image('/photos/g2.jpeg', "Pack Especial de Cookies"),
      image('/photos/c01.jpg', "Pack Especial de Cookies"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/pack-especial-de-cookies',
        name: "escolhe as cookies",
        values: ["3 unidades", "6 unidades", "9 unidades"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/pack-especial-de-cookies-0',
        title: "3 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(18),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "3 unidades" }],
        sku: "pack-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/pack-especial-de-cookies-1',
        title: "6 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(30),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "6 unidades" }],
        sku: "pack-2",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/pack-especial-de-cookies-2',
        title: "9 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(43),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "9 unidades" }],
        sku: "pack-3",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(18),
      maxVariantPrice: money(43),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "cookies",
      badge: "mix de sabores",
      shortDescription: null,
      ingredients: "Ver ingredientes de cada cookie. Cada cookie cont\u00e9m 100 gramas.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/personalizadas',
    handle: "cookies-personalizadas",
    title: "Cookies Personalizadas",
    description: "As nossas cookies com o teu adesivo \u2014 uma imagem ou um desenho teu. M\u00ednimo de 10 unidades, mix de sabores. Perfeito para o teu evento.",
    descriptionHtml: "<p>As nossas cookies com o teu adesivo \u2014 uma imagem ou um desenho teu. M\u00ednimo de 10 unidades, mix de sabores. Perfeito para o teu evento.</p>",
    productType: "cookies",
    vendor: 'Ophelia',
    tags: ["para eventos"],
    availableForSale: true,
    featuredImage: image('/photos/g2.jpeg', "Cookies Personalizadas"),
    images: [
      image('/photos/g2.jpeg', "Cookies Personalizadas"),
      image('/photos/g1.jpeg', "Cookies Personalizadas"),
      image('/photos/c06.jpg', "Cookies Personalizadas"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/cookies-personalizadas',
        name: "escolhe as cookies",
        values: ["10 unidades", "25 unidades", "35 unidades", "50 unidades"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/cookies-personalizadas-0',
        title: "10 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(35),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "10 unidades" }],
        sku: "personalizadas-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/cookies-personalizadas-1',
        title: "25 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(87),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "25 unidades" }],
        sku: "personalizadas-2",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/cookies-personalizadas-2',
        title: "35 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(122),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "35 unidades" }],
        sku: "personalizadas-3",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/cookies-personalizadas-3',
        title: "50 unidades",
        availableForSale: true,
        quantityAvailable: null,
        price: money(175),
        compareAtPrice: null,
        selectedOptions: [{ name: "escolhe as cookies", value: "50 unidades" }],
        sku: "personalizadas-4",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(35),
      maxVariantPrice: money(175),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "cookies",
      badge: "para eventos",
      shortDescription: null,
      ingredients: "Farinha, chocolate 70%, chocolate 36,5%, chocolate branco, manteiga, a\u00e7\u00facares, ovos, gemas, baunilha, bicarbonato, fermento, sal, cacau, corante vermelho, leite em p\u00f3, amido de milho, lim\u00e3o. Cada cookie cont\u00e9m 60 gramas.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/azeite',
    handle: "o-azeite-da-ophelia",
    title: "O Azeite da Ophelia",
    description: "Azeite extra virgem de oliveiras de um sop\u00e9 da Serra da Estrela. Trouxemos o que h\u00e1 de melhor na montanha da Guarda, onde a Ophelia nasceu.",
    descriptionHtml: "<p>Azeite extra virgem de oliveiras de um sop\u00e9 da Serra da Estrela. Trouxemos o que h\u00e1 de melhor na montanha da Guarda, onde a Ophelia nasceu.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["serra da estrela"],
    availableForSale: true,
    featuredImage: image('/photos/g4.jpeg', "O Azeite da Ophelia"),
    images: [
      image('/photos/g4.jpeg', "O Azeite da Ophelia"),
      image('/photos/g3.jpeg', "O Azeite da Ophelia"),
      image('/photos/k05.jpg', "O Azeite da Ophelia"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/o-azeite-da-ophelia',
        name: "tamanho",
        values: ["500 ml", "750 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/o-azeite-da-ophelia-0',
        title: "500 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(13.9),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "500 ml" }],
        sku: "azeite-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/o-azeite-da-ophelia-1',
        title: "750 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(19.9),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "750 ml" }],
        sku: "azeite-2",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(13.9),
      maxVariantPrice: money(19.9),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "serra da estrela",
      shortDescription: null,
      ingredients: "Azeite puro extra virgem.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/mel-rosmaninho',
    handle: "mel-de-rosmaninho",
    title: "Mel de Rosmaninho",
    description: "Com predomin\u00e2ncia pol\u00ednica de rosmaninho, tom claro-\u00e2mbar, suave e de textura fina e leve. Colhido entre julho e agosto.",
    descriptionHtml: "<p>Com predomin\u00e2ncia pol\u00ednica de rosmaninho, tom claro-\u00e2mbar, suave e de textura fina e leve. Colhido entre julho e agosto.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["colhido em julho"],
    availableForSale: true,
    featuredImage: image('/photos/g3.jpeg', "Mel de Rosmaninho"),
    images: [
      image('/photos/g3.jpeg', "Mel de Rosmaninho"),
      image('/photos/g4.jpeg', "Mel de Rosmaninho"),
      image('/photos/p28.jpg', "Mel de Rosmaninho"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/mel-de-rosmaninho',
        name: "tamanho",
        values: ["300 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/mel-de-rosmaninho-0',
        title: "300 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(7.8),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "300 ml" }],
        sku: "mel-rosmaninho-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(7.8),
      maxVariantPrice: money(7.8),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "colhido em julho",
      shortDescription: null,
      ingredients: "Mel puro. A cristaliza\u00e7\u00e3o do mel \u00e9 a garantia de pureza, podendo ser eliminada em banho-maria a 40 graus.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/mel-carvalho',
    handle: "mel-de-carvalho",
    title: "Mel de Carvalho",
    description: "Cor escura com notas avermelhadas, sabor intenso e ligeiramente amargo. Para quem gosta de mel a s\u00e9rio.",
    descriptionHtml: "<p>Cor escura com notas avermelhadas, sabor intenso e ligeiramente amargo. Para quem gosta de mel a s\u00e9rio.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["sabor intenso"],
    availableForSale: true,
    featuredImage: image('/photos/g3.jpeg', "Mel de Carvalho"),
    images: [
      image('/photos/g3.jpeg', "Mel de Carvalho"),
      image('/photos/g4.jpeg', "Mel de Carvalho"),
      image('/photos/p29.jpg', "Mel de Carvalho"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/mel-de-carvalho',
        name: "tamanho",
        values: ["300 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/mel-de-carvalho-0',
        title: "300 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(7.8),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "300 ml" }],
        sku: "mel-carvalho-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(7.8),
      maxVariantPrice: money(7.8),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "sabor intenso",
      shortDescription: null,
      ingredients: "Mel puro. A cristaliza\u00e7\u00e3o do mel \u00e9 a garantia de pureza, podendo ser eliminada em banho-maria a 40 graus.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/doce-alperce',
    handle: "doce-de-alperce-e-amendoa",
    title: "Doce de Alperce e Am\u00eandoa",
    description: "Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.",
    descriptionHtml: "<p>Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["artesanal"],
    availableForSale: true,
    featuredImage: image('/photos/g3.jpeg', "Doce de Alperce e Am\u00eandoa"),
    images: [
      image('/photos/g3.jpeg', "Doce de Alperce e Am\u00eandoa"),
      image('/photos/c05.jpg', "Doce de Alperce e Am\u00eandoa"),
      image('/photos/g4.jpeg', "Doce de Alperce e Am\u00eandoa"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/doce-de-alperce-e-amendoa',
        name: "tamanho",
        values: ["225 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/doce-de-alperce-e-amendoa-0',
        title: "225 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(4.85),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "225 ml" }],
        sku: "doce-alperce-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(4.85),
      maxVariantPrice: money(4.85),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "artesanal",
      shortDescription: null,
      ingredients: "Alperce, am\u00eandoa, \u00e1gua, a\u00e7\u00facar, lim\u00e3o.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/doce-maca',
    handle: "doce-de-maca-e-vinho-do-porto",
    title: "Doce de Ma\u00e7\u00e3 e Vinho do Porto",
    description: "Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.",
    descriptionHtml: "<p>Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["artesanal"],
    availableForSale: true,
    featuredImage: image('/photos/g3.jpeg', "Doce de Ma\u00e7\u00e3 e Vinho do Porto"),
    images: [
      image('/photos/g3.jpeg', "Doce de Ma\u00e7\u00e3 e Vinho do Porto"),
      image('/photos/c05.jpg', "Doce de Ma\u00e7\u00e3 e Vinho do Porto"),
      image('/photos/g4.jpeg', "Doce de Ma\u00e7\u00e3 e Vinho do Porto"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/doce-de-maca-e-vinho-do-porto',
        name: "tamanho",
        values: ["225 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/doce-de-maca-e-vinho-do-porto-0',
        title: "225 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(4.85),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "225 ml" }],
        sku: "doce-maca-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(4.85),
      maxVariantPrice: money(4.85),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "artesanal",
      shortDescription: null,
      ingredients: "Ma\u00e7\u00e3, a\u00e7\u00facar amarelo, vinho do Porto.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/doce-pera',
    handle: "doce-de-pera-e-gengibre",
    title: "Doce de Pera e Gengibre",
    description: "Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.",
    descriptionHtml: "<p>Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["artesanal"],
    availableForSale: true,
    featuredImage: image('/photos/g3.jpeg', "Doce de Pera e Gengibre"),
    images: [
      image('/photos/g3.jpeg', "Doce de Pera e Gengibre"),
      image('/photos/c05.jpg', "Doce de Pera e Gengibre"),
      image('/photos/g4.jpeg', "Doce de Pera e Gengibre"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/doce-de-pera-e-gengibre',
        name: "tamanho",
        values: ["225 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/doce-de-pera-e-gengibre-0',
        title: "225 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(4.85),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "225 ml" }],
        sku: "doce-pera-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(4.85),
      maxVariantPrice: money(4.85),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "artesanal",
      shortDescription: null,
      ingredients: "Pera rocha, gengibre e a\u00e7\u00facar.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/doce-morango',
    handle: "doce-de-morango-com-baunilha",
    title: "Doce de Morango com Baunilha",
    description: "Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.",
    descriptionHtml: "<p>Quatro sabores \u00fanicos de doces caseiros, feitos apenas com fruta e a\u00e7\u00facar, de forma totalmente artesanal.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["artesanal"],
    availableForSale: true,
    featuredImage: image('/photos/g3.jpeg', "Doce de Morango com Baunilha"),
    images: [
      image('/photos/g3.jpeg', "Doce de Morango com Baunilha"),
      image('/photos/c05.jpg', "Doce de Morango com Baunilha"),
      image('/photos/g4.jpeg', "Doce de Morango com Baunilha"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/doce-de-morango-com-baunilha',
        name: "tamanho",
        values: ["225 ml"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/doce-de-morango-com-baunilha-0',
        title: "225 ml",
        availableForSale: true,
        quantityAvailable: null,
        price: money(4.85),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "225 ml" }],
        sku: "doce-morango-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(4.85),
      maxVariantPrice: money(4.85),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "artesanal",
      shortDescription: null,
      ingredients: "Morango, a\u00e7\u00facar, vagem de baunilha.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/granola',
    handle: "a-granola-da-ophelia",
    title: "A Granola da Ophelia",
    description: "Diariamente fazemos granola na loja. O cheirinho de frutos secos caramelizados invade tudo e ningu\u00e9m lhe resiste. \u00c9 a melhor do mundo \u2014 podemos garantir.",
    descriptionHtml: "<p>Diariamente fazemos granola na loja. O cheirinho de frutos secos caramelizados invade tudo e ningu\u00e9m lhe resiste. \u00c9 a melhor do mundo \u2014 podemos garantir.</p>",
    productType: "mercearia",
    vendor: 'Ophelia',
    tags: ["feita todos os dias"],
    availableForSale: true,
    featuredImage: image('/photos/p28.jpg', "A Granola da Ophelia"),
    images: [
      image('/photos/p28.jpg', "A Granola da Ophelia"),
      image('/photos/p29.jpg', "A Granola da Ophelia"),
      image('/photos/p30.jpg', "A Granola da Ophelia"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/a-granola-da-ophelia',
        name: "tamanho",
        values: ["300 gramas", "600 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/a-granola-da-ophelia-0',
        title: "300 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(8),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "300 gramas" }],
        sku: "granola-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/a-granola-da-ophelia-1',
        title: "600 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(14),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "600 gramas" }],
        sku: "granola-2",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(8),
      maxVariantPrice: money(14),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "mercearia",
      badge: "feita todos os dias",
      shortDescription: null,
      ingredients: "Aveia, flocos de milho, noz, caju, pist\u00e1cio, avel\u00e3, am\u00eandoa, noz-pec\u00e3, coco laminado, mel e canela.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/cafe-grao',
    handle: "cafe-da-ophelia-em-grao",
    title: "Caf\u00e9 da Ophelia \u00b7 em gr\u00e3o",
    description: "O nosso blend exclusivo combina 70% Brasil e 30% Eti\u00f3pia: notas suaves, achocolatadas e de frutos secos com a eleg\u00e2ncia floral e os toques c\u00edtricos et\u00edopes. Torrado na nossa loja todos os dias, por n\u00f3s.",
    descriptionHtml: "<p>O nosso blend exclusivo combina 70% Brasil e 30% Eti\u00f3pia: notas suaves, achocolatadas e de frutos secos com a eleg\u00e2ncia floral e os toques c\u00edtricos et\u00edopes. Torrado na nossa loja todos os dias, por n\u00f3s.</p>",
    productType: "caf\u00e9, chai & matcha",
    vendor: 'Ophelia',
    tags: ["torrado na loja"],
    availableForSale: true,
    featuredImage: image('/photos/b05.jpg', "Caf\u00e9 da Ophelia \u00b7 em gr\u00e3o"),
    images: [
      image('/photos/b05.jpg', "Caf\u00e9 da Ophelia \u00b7 em gr\u00e3o"),
      image('/photos/b10.jpg', "Caf\u00e9 da Ophelia \u00b7 em gr\u00e3o"),
      image('/photos/b06.jpg', "Caf\u00e9 da Ophelia \u00b7 em gr\u00e3o"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/cafe-da-ophelia-em-grao',
        name: "tamanho",
        values: ["250 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/cafe-da-ophelia-em-grao-0',
        title: "250 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(18),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "250 gramas" }],
        sku: "cafe-grao-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(18),
      maxVariantPrice: money(18),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "caf\u00e9, chai & matcha",
      badge: "torrado na loja",
      shortDescription: null,
      ingredients: "Gr\u00e3o de caf\u00e9: 70% Brasil, 30% Eti\u00f3pia.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/cafe-po',
    handle: "cafe-da-ophelia-em-po",
    title: "Caf\u00e9 da Ophelia \u00b7 em p\u00f3",
    description: "O mesmo blend 70% Brasil e 30% Eti\u00f3pia, mo\u00eddo na loja para a tua cafeteira. Do\u00e7ura natural, corpo m\u00e9dio e um aroma vibrante.",
    descriptionHtml: "<p>O mesmo blend 70% Brasil e 30% Eti\u00f3pia, mo\u00eddo na loja para a tua cafeteira. Do\u00e7ura natural, corpo m\u00e9dio e um aroma vibrante.</p>",
    productType: "caf\u00e9, chai & matcha",
    vendor: 'Ophelia',
    tags: ["mo\u00eddo por n\u00f3s"],
    availableForSale: true,
    featuredImage: image('/photos/b06.jpg', "Caf\u00e9 da Ophelia \u00b7 em p\u00f3"),
    images: [
      image('/photos/b06.jpg', "Caf\u00e9 da Ophelia \u00b7 em p\u00f3"),
      image('/photos/b05.jpg', "Caf\u00e9 da Ophelia \u00b7 em p\u00f3"),
      image('/photos/b12.jpg', "Caf\u00e9 da Ophelia \u00b7 em p\u00f3"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/cafe-da-ophelia-em-po',
        name: "tamanho",
        values: ["250 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/cafe-da-ophelia-em-po-0',
        title: "250 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(8),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "250 gramas" }],
        sku: "cafe-po-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(8),
      maxVariantPrice: money(8),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "caf\u00e9, chai & matcha",
      badge: "mo\u00eddo por n\u00f3s",
      shortDescription: null,
      ingredients: "Gr\u00e3o de caf\u00e9 mo\u00eddo: 70% Brasil, 30% Eti\u00f3pia.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/chai',
    handle: "chai-da-ophelia",
    title: "Chai da Ophelia",
    description: "O nosso chai, feito com a mistura de especiarias que usamos na loja. Encorpado, doce e reconfortante \u2014 perfeito com leite bem quente.",
    descriptionHtml: "<p>O nosso chai, feito com a mistura de especiarias que usamos na loja. Encorpado, doce e reconfortante \u2014 perfeito com leite bem quente.</p>",
    productType: "caf\u00e9, chai & matcha",
    vendor: 'Ophelia',
    tags: ["especiarias"],
    availableForSale: true,
    featuredImage: image('/photos/b03.jpg', "Chai da Ophelia"),
    images: [
      image('/photos/b03.jpg', "Chai da Ophelia"),
      image('/photos/b04.jpg', "Chai da Ophelia"),
      image('/photos/b12.jpg', "Chai da Ophelia"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/chai-da-ophelia',
        name: "tamanho",
        values: ["250 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/chai-da-ophelia-0',
        title: "250 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(18),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "250 gramas" }],
        sku: "chai-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(18),
      maxVariantPrice: money(18),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "caf\u00e9, chai & matcha",
      badge: "especiarias",
      shortDescription: null,
      ingredients: "Ch\u00e1 preto, canela, gengibre, cardamomo, cravinho, pimenta.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/matcha',
    handle: "matcha-da-ophelia",
    title: "Matcha da Ophelia",
    description: "O matcha que servimos na loja: verde vivo, cremoso e sem amargo. Bate bem com \u00e1gua morna ou direto no leite gelado.",
    descriptionHtml: "<p>O matcha que servimos na loja: verde vivo, cremoso e sem amargo. Bate bem com \u00e1gua morna ou direto no leite gelado.</p>",
    productType: "caf\u00e9, chai & matcha",
    vendor: 'Ophelia',
    tags: ["grau cerimonial"],
    availableForSale: true,
    featuredImage: image('/photos/b07.jpg', "Matcha da Ophelia"),
    images: [
      image('/photos/b07.jpg', "Matcha da Ophelia"),
      image('/photos/b04.jpg', "Matcha da Ophelia"),
      image('/photos/b05.jpg', "Matcha da Ophelia"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/matcha-da-ophelia',
        name: "tamanho",
        values: ["250 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/matcha-da-ophelia-0',
        title: "250 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(18),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "250 gramas" }],
        sku: "matcha-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(18),
      maxVariantPrice: money(18),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "caf\u00e9, chai & matcha",
      badge: "grau cerimonial",
      shortDescription: null,
      ingredients: "Ch\u00e1 verde matcha 100%.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/bolo-chocolate',
    handle: "bolo-de-chocolate-e-framboesa",
    title: "Bolo de Chocolate e Framboesa",
    description: "Camadas de chocolate 70% com creme de framboesa fresca. Feito sob encomenda com 48 horas de anteced\u00eancia. Para recolher na loja ou entrega em Lisboa e Estoril.",
    descriptionHtml: "<p>Camadas de chocolate 70% com creme de framboesa fresca. Feito sob encomenda com 48 horas de anteced\u00eancia. Para recolher na loja ou entrega em Lisboa e Estoril.</p>",
    productType: "bolos",
    vendor: 'Ophelia',
    tags: ["por encomenda"],
    availableForSale: true,
    featuredImage: image('/photos/n17.jpg', "Bolo de Chocolate e Framboesa"),
    images: [
      image('/photos/n17.jpg', "Bolo de Chocolate e Framboesa"),
      image('/photos/n05.jpg', "Bolo de Chocolate e Framboesa"),
      image('/photos/k10.jpg', "Bolo de Chocolate e Framboesa"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/bolo-de-chocolate-e-framboesa',
        name: "serve",
        values: ["8 a 10 pessoas", "14 a 16 pessoas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/bolo-de-chocolate-e-framboesa-0',
        title: "8 a 10 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(38),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "8 a 10 pessoas" }],
        sku: "bolo-chocolate-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/bolo-de-chocolate-e-framboesa-1',
        title: "14 a 16 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(54),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "14 a 16 pessoas" }],
        sku: "bolo-chocolate-2",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(38),
      maxVariantPrice: money(54),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "bolos",
      badge: "por encomenda",
      shortDescription: null,
      ingredients: "Chocolate 70%, manteiga, a\u00e7\u00facar, ovos, farinha, framboesa, nata.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/pavlova',
    handle: "pavlova-de-frutos-vermelhos",
    title: "Pavlova de Frutos Vermelhos",
    description: "Merengue crocante por fora, macio por dentro, com chantilly e frutos vermelhos da \u00e9poca. Fr\u00e1gil, exagerada e a nossa favorita para festas.",
    descriptionHtml: "<p>Merengue crocante por fora, macio por dentro, com chantilly e frutos vermelhos da \u00e9poca. Fr\u00e1gil, exagerada e a nossa favorita para festas.</p>",
    productType: "bolos",
    vendor: 'Ophelia',
    tags: ["por encomenda"],
    availableForSale: true,
    featuredImage: image('/photos/a01.jpg', "Pavlova de Frutos Vermelhos"),
    images: [
      image('/photos/a01.jpg', "Pavlova de Frutos Vermelhos"),
      image('/photos/a08.jpg', "Pavlova de Frutos Vermelhos"),
      image('/photos/c02.jpg', "Pavlova de Frutos Vermelhos"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/pavlova-de-frutos-vermelhos',
        name: "serve",
        values: ["8 a 10 pessoas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/pavlova-de-frutos-vermelhos-0',
        title: "8 a 10 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(34),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "8 a 10 pessoas" }],
        sku: "pavlova-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(34),
      maxVariantPrice: money(34),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "bolos",
      badge: "por encomenda",
      shortDescription: null,
      ingredients: "Claras, a\u00e7\u00facar, vinagre, amido de milho, nata, frutos vermelhos.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/red-velvet',
    handle: "bolo-red-velvet",
    title: "Bolo Red Velvet",
    description: "O cl\u00e1ssico da casa: massa vermelha muito h\u00famida e creme de queijo. Vai coberto de frutos vermelhos frescos.",
    descriptionHtml: "<p>O cl\u00e1ssico da casa: massa vermelha muito h\u00famida e creme de queijo. Vai coberto de frutos vermelhos frescos.</p>",
    productType: "bolos",
    vendor: 'Ophelia',
    tags: ["por encomenda"],
    availableForSale: true,
    featuredImage: image('/photos/n18.jpg', "Bolo Red Velvet"),
    images: [
      image('/photos/n18.jpg', "Bolo Red Velvet"),
      image('/photos/n17.jpg', "Bolo Red Velvet"),
      image('/photos/n26.jpg', "Bolo Red Velvet"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/bolo-red-velvet',
        name: "serve",
        values: ["8 a 10 pessoas", "14 a 16 pessoas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/bolo-red-velvet-0',
        title: "8 a 10 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(36),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "8 a 10 pessoas" }],
        sku: "red-velvet-1",
        image: null,
      },
      {
        id: 'gid://fixture/ProductVariant/bolo-red-velvet-1',
        title: "14 a 16 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(52),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "14 a 16 pessoas" }],
        sku: "red-velvet-2",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(36),
      maxVariantPrice: money(52),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "bolos",
      badge: "por encomenda",
      shortDescription: null,
      ingredients: "Farinha, cacau, corante, manteiga, a\u00e7\u00facar, ovos, buttermilk, queijo creme.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/caramelo',
    handle: "bolo-merengue-de-caramelo",
    title: "Bolo Merengue de Caramelo",
    description: "Bolo de baunilha com merengue queimado e caramelo salgado a escorrer. O que costuma desaparecer primeiro \u00e0 mesa.",
    descriptionHtml: "<p>Bolo de baunilha com merengue queimado e caramelo salgado a escorrer. O que costuma desaparecer primeiro \u00e0 mesa.</p>",
    productType: "bolos",
    vendor: 'Ophelia',
    tags: ["por encomenda"],
    availableForSale: true,
    featuredImage: image('/photos/n21.jpg', "Bolo Merengue de Caramelo"),
    images: [
      image('/photos/n21.jpg', "Bolo Merengue de Caramelo"),
      image('/photos/n23.jpg', "Bolo Merengue de Caramelo"),
      image('/photos/n27.jpg', "Bolo Merengue de Caramelo"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/bolo-merengue-de-caramelo',
        name: "serve",
        values: ["8 a 10 pessoas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/bolo-merengue-de-caramelo-0',
        title: "8 a 10 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(36),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "8 a 10 pessoas" }],
        sku: "caramelo-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(36),
      maxVariantPrice: money(36),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "bolos",
      badge: "por encomenda",
      shortDescription: null,
      ingredients: "Farinha, manteiga, a\u00e7\u00facar, ovos, baunilha, nata, caramelo salgado.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/cheesecake',
    handle: "cheesecake-de-frutos-silvestres",
    title: "Cheesecake de Frutos Silvestres",
    description: "Cheesecake cremoso sobre base de bolacha, com compota de frutos silvestres feita por n\u00f3s.",
    descriptionHtml: "<p>Cheesecake cremoso sobre base de bolacha, com compota de frutos silvestres feita por n\u00f3s.</p>",
    productType: "bolos",
    vendor: 'Ophelia',
    tags: ["por encomenda"],
    availableForSale: true,
    featuredImage: image('/photos/n15.jpg', "Cheesecake de Frutos Silvestres"),
    images: [
      image('/photos/n15.jpg', "Cheesecake de Frutos Silvestres"),
      image('/photos/n16.jpg', "Cheesecake de Frutos Silvestres"),
      image('/photos/a06.jpg', "Cheesecake de Frutos Silvestres"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/cheesecake-de-frutos-silvestres',
        name: "serve",
        values: ["8 a 10 pessoas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/cheesecake-de-frutos-silvestres-0',
        title: "8 a 10 pessoas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(32),
        compareAtPrice: null,
        selectedOptions: [{ name: "serve", value: "8 a 10 pessoas" }],
        sku: "cheesecake-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(32),
      maxVariantPrice: money(32),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "bolos",
      badge: "por encomenda",
      shortDescription: null,
      ingredients: "Bolacha, manteiga, queijo creme, nata, a\u00e7\u00facar, ovos, frutos silvestres.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/panetone',
    handle: "panetone-de-chocolate",
    title: "Panetone de Chocolate",
    description: "Massa fofa de fermenta\u00e7\u00e3o lenta, coberta de chocolate. Fazemos apenas em dezembro, em quantidades pequenas.",
    descriptionHtml: "<p>Massa fofa de fermenta\u00e7\u00e3o lenta, coberta de chocolate. Fazemos apenas em dezembro, em quantidades pequenas.</p>",
    productType: "bolos",
    vendor: 'Ophelia',
    tags: ["\u00e9poca de natal"],
    availableForSale: true,
    featuredImage: image('/photos/n12.jpg', "Panetone de Chocolate"),
    images: [
      image('/photos/n12.jpg', "Panetone de Chocolate"),
      image('/photos/n11.jpg', "Panetone de Chocolate"),
      image('/photos/n13.jpg', "Panetone de Chocolate"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/panetone-de-chocolate',
        name: "tamanho",
        values: ["750 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/panetone-de-chocolate-0',
        title: "750 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(28),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "750 gramas" }],
        sku: "panetone-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(28),
      maxVariantPrice: money(28),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "bolos",
      badge: "\u00e9poca de natal",
      shortDescription: null,
      ingredients: "Farinha, manteiga, ovos, a\u00e7\u00facar, fermento natural, chocolate.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/vela',
    handle: "vela-aromatica-croissant",
    title: "Vela Arom\u00e1tica Croissant",
    description: "O cheirinho dela \u00e9 delicioso, d\u00e1 vontade de comer. \u00c9 exatamente o aroma da nossa loja \u00e0s nove da manh\u00e3.",
    descriptionHtml: "<p>O cheirinho dela \u00e9 delicioso, d\u00e1 vontade de comer. \u00c9 exatamente o aroma da nossa loja \u00e0s nove da manh\u00e3.</p>",
    productType: "casa & presentes",
    vendor: 'Ophelia',
    tags: ["cheira a loja"],
    availableForSale: true,
    featuredImage: image('/photos/p01.jpg', "Vela Arom\u00e1tica Croissant"),
    images: [
      image('/photos/p01.jpg', "Vela Arom\u00e1tica Croissant"),
      image('/photos/e03.jpg', "Vela Arom\u00e1tica Croissant"),
      image('/photos/p26.jpg', "Vela Arom\u00e1tica Croissant"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/vela-aromatica-croissant',
        name: "tamanho",
        values: ["250 gramas"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/vela-aromatica-croissant-0',
        title: "250 gramas",
        availableForSale: true,
        quantityAvailable: null,
        price: money(18),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "250 gramas" }],
        sku: "vela-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(18),
      maxVariantPrice: money(18),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "casa & presentes",
      badge: "cheira a loja",
      shortDescription: null,
      ingredients: "Cera vegetal, \u00f3leos essenciais e fragr\u00e2ncia. Pavio de algod\u00e3o.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/avental',
    handle: "avental-da-ophelia",
    title: "Avental da Ophelia",
    description: "Cri\u00e1mos um padr\u00e3o \u00fanico e muito divertido para que todos possam experimentar as nossas receitas \u2014 e, principalmente, partilh\u00e1-las com a fam\u00edlia.",
    descriptionHtml: "<p>Cri\u00e1mos um padr\u00e3o \u00fanico e muito divertido para que todos possam experimentar as nossas receitas \u2014 e, principalmente, partilh\u00e1-las com a fam\u00edlia.</p>",
    productType: "casa & presentes",
    vendor: 'Ophelia',
    tags: ["100% algod\u00e3o"],
    availableForSale: true,
    featuredImage: image('/photos/a09.jpg', "Avental da Ophelia"),
    images: [
      image('/photos/a09.jpg', "Avental da Ophelia"),
      image('/photos/k07.jpg', "Avental da Ophelia"),
      image('/photos/k02.jpg', "Avental da Ophelia"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/avental-da-ophelia',
        name: "tamanho",
        values: ["tamanho \u00fanico"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/avental-da-ophelia-0',
        title: "tamanho \u00fanico",
        availableForSale: true,
        quantityAvailable: null,
        price: money(24),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "tamanho \u00fanico" }],
        sku: "avental-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(24),
      maxVariantPrice: money(24),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "casa & presentes",
      badge: "100% algod\u00e3o",
      shortDescription: null,
      ingredients: "100% algod\u00e3o. Lavar a 30 graus.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'gid://fixture/Product/cartao',
    handle: "cartao-personalizado",
    title: "Cart\u00e3o Personalizado",
    description: "Escrevemos \u00e0 m\u00e3o o teu recado e juntamos ao pacote. Dizem-nos que \u00e9 a parte que abrem primeiro.",
    descriptionHtml: "<p>Escrevemos \u00e0 m\u00e3o o teu recado e juntamos ao pacote. Dizem-nos que \u00e9 a parte que abrem primeiro.</p>",
    productType: "casa & presentes",
    vendor: 'Ophelia',
    tags: ["escrito \u00e0 m\u00e3o"],
    availableForSale: true,
    featuredImage: image('/photos/g5.jpeg', "Cart\u00e3o Personalizado"),
    images: [
      image('/photos/g5.jpeg', "Cart\u00e3o Personalizado"),
      image('/photos/g6.jpeg', "Cart\u00e3o Personalizado"),
      image('/photos/e03.jpg', "Cart\u00e3o Personalizado"),
    ],
    options: [
      {
        id: 'gid://fixture/ProductOption/cartao-personalizado',
        name: "tamanho",
        values: ["um cart\u00e3o"],
      },
    ],
    variants: [
      {
        id: 'gid://fixture/ProductVariant/cartao-personalizado-0',
        title: "um cart\u00e3o",
        availableForSale: true,
        quantityAvailable: null,
        price: money(4),
        compareAtPrice: null,
        selectedOptions: [{ name: "tamanho", value: "um cart\u00e3o" }],
        sku: "cartao-1",
        image: null,
      },
    ],
    priceRange: {
      minVariantPrice: money(4),
      maxVariantPrice: money(4),
    },
    seo: { title: null, description: null },
    editorial: {
      kicker: "casa & presentes",
      badge: "escrito \u00e0 m\u00e3o",
      shortDescription: null,
      ingredients: "Papel de algod\u00e3o, impresso e escrito por n\u00f3s.",
    },
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

/** Hand-picked cross-sells from the handoff, as product handles. */
export const FIXTURE_SUGGESTIONS: Record<string, string[]> = {
  "ophelia-cookies-ny": ["a-granola-da-ophelia", "cafe-da-ophelia-em-grao", "vela-aromatica-croissant"],
  "ophelia-cookies": ["a-granola-da-ophelia", "mel-de-rosmaninho", "vela-aromatica-croissant"],
  "ophelia-cookiebrownie": ["o-azeite-da-ophelia", "cafe-da-ophelia-em-grao", "vela-aromatica-croissant"],
  "ophelia-cookie-banoffee": ["o-azeite-da-ophelia", "a-granola-da-ophelia", "vela-aromatica-croissant"],
  "pack-especial-de-cookies": ["cafe-da-ophelia-em-grao", "a-granola-da-ophelia", "mel-de-carvalho"],
  "cookies-personalizadas": ["cartao-personalizado", "a-granola-da-ophelia", "cafe-da-ophelia-em-grao"],
  "o-azeite-da-ophelia": ["mel-de-rosmaninho", "a-granola-da-ophelia", "vela-aromatica-croissant"],
  "mel-de-rosmaninho": ["o-azeite-da-ophelia", "a-granola-da-ophelia", "doce-de-morango-com-baunilha"],
  "mel-de-carvalho": ["o-azeite-da-ophelia", "a-granola-da-ophelia", "pack-especial-de-cookies"],
  "doce-de-alperce-e-amendoa": ["a-granola-da-ophelia", "pack-especial-de-cookies", "mel-de-rosmaninho"],
  "doce-de-maca-e-vinho-do-porto": ["o-azeite-da-ophelia", "a-granola-da-ophelia", "mel-de-rosmaninho"],
  "doce-de-pera-e-gengibre": ["o-azeite-da-ophelia", "a-granola-da-ophelia", "mel-de-rosmaninho"],
  "doce-de-morango-com-baunilha": ["a-granola-da-ophelia", "pack-especial-de-cookies", "mel-de-carvalho"],
  "a-granola-da-ophelia": ["mel-de-rosmaninho", "cafe-da-ophelia-em-grao", "o-azeite-da-ophelia"],
  "cafe-da-ophelia-em-grao": ["a-granola-da-ophelia", "ophelia-cookiebrownie", "vela-aromatica-croissant"],
  "cafe-da-ophelia-em-po": ["a-granola-da-ophelia", "o-azeite-da-ophelia", "vela-aromatica-croissant"],
  "chai-da-ophelia": ["a-granola-da-ophelia", "ophelia-cookiebrownie", "pack-especial-de-cookies"],
  "matcha-da-ophelia": ["a-granola-da-ophelia", "ophelia-cookies", "vela-aromatica-croissant"],
  "bolo-de-chocolate-e-framboesa": ["cafe-da-ophelia-em-grao", "pack-especial-de-cookies", "cartao-personalizado"],
  "pavlova-de-frutos-vermelhos": ["cafe-da-ophelia-em-po", "matcha-da-ophelia", "cartao-personalizado"],
  "bolo-red-velvet": ["chai-da-ophelia", "cafe-da-ophelia-em-grao", "cartao-personalizado"],
  "bolo-merengue-de-caramelo": ["cafe-da-ophelia-em-grao", "a-granola-da-ophelia", "cartao-personalizado"],
  "cheesecake-de-frutos-silvestres": ["cafe-da-ophelia-em-po", "doce-de-morango-com-baunilha", "cartao-personalizado"],
  "panetone-de-chocolate": ["cafe-da-ophelia-em-grao", "chai-da-ophelia", "cartao-personalizado"],
  "vela-aromatica-croissant": ["cafe-da-ophelia-em-grao", "a-granola-da-ophelia", "ophelia-cookiebrownie"],
  "avental-da-ophelia": ["a-granola-da-ophelia", "cafe-da-ophelia-em-grao", "vela-aromatica-croissant"],
  "cartao-personalizado": ["ophelia-cookies-ny", "a-granola-da-ophelia", "vela-aromatica-croissant"],
};
